config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cars

  get '/cars/users/:user_id', to: 'cars#mine', as: :cars_mine

  resources :bookings, only: [:new, :create, :destroy]
  patch '/bookings/:id/accept', to: 'bookings#accept', as: :accept_booking
  patch '/bookings/:id/decline', to: 'bookings#decline', as: :decline_booking
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_cardcategory.html.erb
<h2 class="category-title">Ideas for your next ride</h2>

<div class="main-container">
    <div class="cards">
        <div class="card" style="background-image: url(https://www.authentic-roads.com/wp-content/uploads/2019/12/1577101521_279_Top-10-des-meilleures-super-voitures-de-sport-2019.jpg)">
          <%= link_to 'Sportscar', cars_path(query: "Sportscar") %>
        </div>
        <div class="card" style="background-image: url(https://i.gaw.to/vehicles/photos/09/24/092472_2019_nissan_Micra.jpg?640x400)">
           <%= link_to 'City Car', cars_path(query: "City Car") %>
        </div>
        <div class="card" style="background-image: url(https://www.automobile-propre.com/wp-content/uploads/2020/12/Nio-ET-Preview-berline-electrique-1.jpg)">
           <%= link_to 'Sedan', cars_path(query: "Sedan") %>
        </div>
    </div>
</div>

app/views/shared/_cardhome.html.erb
<%# card home %>

<div class="card-category mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.pexels.com/photos/53537/caravan-desert-safari-dune-53537.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260')">
  <h1>You don't know what to drive ?</h1>
  <%= link_to "I'm flexible", cars_path, class:"btn btn-flat btn-flex" %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/chrisLaf388/rails_cars_location"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonmarseille/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/lewagonfrance"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/LeWagonMrs"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/showcase/le-wagon-marseille/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a  href="https://airbnb-chrislaf388.herokuapp.com/" class="navbar-brand">
    <div class="logo">
      <i class="fas fa-car"></i>
    </div>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item nav-link">
        User: <%= current_user.id %>
      </li>
      <li class="nav-item nav-link">
        <%= current_user.email %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link", id:"navbar-links" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Cars', cars_path, class:"nav-link", id:"navbar-links" %>
      </li>
      <li class="nav-item dropdown">
        <img id="navbar-links" class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://media.istockphoto.com/vectors/user-icon-flat-isolated-on-white-background-user-symbol-vector-vector-id1300845620?b=1&k=20&m=1300845620&s=170667a&w=0&h=JbOeyFgAc6-3jmptv6mzXpGcAd_8xqkQa_oUK2viFr8=" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if user_signed_in? %>
        <%= link_to 'Dashboard', dashboard_path, class:"dropdown-item" %>
        <%= link_to "Sign-out?",
            destroy_user_session_path,
            method: :delete,
            class: "dropdown-item",
            data: { confirm: "Are you sure?" } %>
        <% else %>
        <%= link_to "Inscription", new_user_registration_path, class:"dropdown-item" %>
        <%= link_to "Connexion", new_user_session_path, class:"dropdown-item" %>
        <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_notificationdashboard.html.erb
<div class="notification">
  <%# <%= link_to car.name, car_path(car), background-image: url(cl_image_path car.photo.key) ,class: "img-large" %>
    <img src= "<%= cl_image_path car.photo.key%>", class="img-large" />

  <div class="notification-content">
    <% if format == "pending" %>
      <p><%= user.email %> wants to drive your <%= link_to car.name, car_path(car) %></p>
    <% elsif format == "booking" %>
      <p>You want wants to drive this <%= link_to car.name, car_path(car) %> Belong : <%= user.email %> </p>
    <% end %>
    <p><strong>From : </strong><small><%= booking.start_at %></small>, <strong>To : </strong><small><%= booking.end_at %></small></p>
    <p class="text-danger"><%= booking.total_price %>€</p>
  </div>

  <div class="notification-actions">
    <% if format == "pending" %>
      <% if booking.status.nil? %>
        <%= link_to accept_booking_path(booking), method: :patch do %>
          <i class="fas fa-check-circle text-success"></i>
        <% end %>
        <%= link_to decline_booking_path(booking), method: :patch do %>
          <i class="fas fa-ban text-danger"></i>
        <% end %>
      <% elsif booking.status.present? %>
        <i class="fas fa-check-circle text-success"></i>
      <% else %>
        <i class="fas fa-ban text-danger"></i>
      <% end %>
    <% elsif format == "booking" %>
      <% if booking.status == true %>
        <i class="fas fa-check-circle text-success"></i>
      <% elsif booking.status == false %>
        <i class="fas fa-ban text-danger"></i>
      <% else %>
        <i class="fas fa-hourglass-half text-info"></i>
      <% end %>
      <%= link_to booking_path(booking),
          method: :delete,
          class: "text-danger",
          data: { confirm: "Are you sure?" } do %>
            <i class="fas fa-trash-alt"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<%# search bar %>
<div id="searchbar">
  <h5>Type anything (brand, city, category...)</h5>
  <%= form_tag cars_path, class: "simple_form search d-flex mt-0", label: "Search", method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      label: "Search",
      class: "form-control string required",
      placeholder: "e.g. Ferrari Marseille"
    %>
    <%= submit_tag "Search", class: "btn btn-flat" %>
  <% end %>
</div>





<%#
<form novalidate="novalidate" class="simple_form search" action="/cars" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="e.g. Ferrari Marseille"/>
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form> %>

app/views/shared/_warriorsearchbar.html.erb
<%= form_tag cars_path, method: :get do |f| %>
  <div>
    <%= label_tag "Model" %>
    <%= text_field_tag :name, params[:name] %>
  </div>
  <div>
    <%= label_tag "Category" %>
    <%= select_tag :category, options_for_select(Car::CATEGORY.dup.unshift("")) %>
  </div>
  <div>
    <%= label_tag "Transmission" %>
    <%= select_tag :transmision, options_for_select(Car::TRANSMISION.dup.unshift("")) %>
  </div>
  <div>
    <%= label_tag "Fuel Type" %>
    <%= select_tag :energy, options_for_select(Car::ENERGY.dup.unshift(""))  %>
  </div>
  <div>
    <%= label_tag "City" %>
    <%= text_field_tag :city, params[:city] %>
  </div>
  <div>
    <%= label_tag "Max. price" %>
    <%= range_field_tag :max_price, params[:max_price] %>
  </div>
  <%= submit_tag "Search", name: nil %>
<% end %>