config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cars

  get '/cars/users/:user_id', to: 'cars#mine', as: :cars_mine

  resources :bookings, only: [:new, :create, :destroy]
  patch '/bookings/:id/accept', to: 'bookings#accept', as: :accept_booking
  patch '/bookings/:id/decline', to: 'bookings#decline', as: :decline_booking
  get '/dashboard', to: 'pages#dashboard', as: :dashboard
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  CATEGORY = ["Sportscar", "City Car", "Sedan", "All Natural", "Supercar", "SUV"]
  TRANSMISION = ["Automatic", "Manual", "Assisted"]
  ENERGY = ["Petrol", "Diesel", "Electrical", "Hybrid", "Renewable"]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORY,
    message: "%{value} is not a valid category" }
  validates :transmision, presence: true, inclusion: { in: TRANSMISION,
    message: "%{value} is not a valid transmission type" }
  validates :energy, presence: true, inclusion: { in: ENERGY,
    message: "%{value} is not a valid fuel type" }
  validates :city, presence: true
  validates :price_per_day, presence: true, numericality: { greater_than: 0 }

  include PgSearch::Model
  pg_search_scope :search_by_name_and_category_city,
    against: [ :name, :category, :city, :transmision, :energy ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  pg_search_scope :search_by_name,
    against: [ :name],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  pg_search_scope :search_by_category,
    against: [ :category],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  pg_search_scope :search_by_energy,
    against: [ :energy],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  pg_search_scope :search_by_transmision,
    against: [ :transmision],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  pg_search_scope :search_by_city,
    against: [ :city],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  # scope :filter_by_name, -> (name) { where("name ILIKE ?", "%#{name}%")}
  # scope :filter_by_category, -> (category) { where("category = ?", category)}
  # scope :filter_by_transmision, -> (transmision) { where("transmision = ?", transmision) }
  # scope :filter_by_energy, -> (energy) { where("energy = ?", energy) }
  # scope :filter_by_max_price, -> (max_price) { where(price_per_day: "<= #{max_price}") }

  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, except: [:index, :new, :create, :car_params, :category]

  def index
    # if params.keys == ["controller", "action"]
      #  @cars = Car.all
    if params["query"].present?
      @cars = Car.search_by_name_and_category_city(params["query"])
    elsif params.keys == ["controller", "action"]
      @cars = policy_scope(Car).order(updated_at: :desc)
    else
      @cars = policy_scope(Car).order(updated_at: :desc)
      @cars = @cars.search_by_name(params["name"]) unless params["name"].empty?
      @cars = @cars.search_by_category(params["category"]) unless params["category"].empty?
      @cars = @cars.search_by_transmision(params["transmision"]) unless params["transmision"].empty?
      @cars = @cars.search_by_energy(params["energy"]) unless params["energy"].empty?
      @cars = @cars.search_by_city(params["city"]) unless params["city"].empty?
    end

    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "info_window", locals: { car: car }),
        image_url: car.photo.key,
        price: car.price_per_day
      }
    end
  end

  def show
    authorize @car
  end

  def edit
    authorize @car
  end

  def update
    authorize @car
    @user = current_user
    @car.user = @user
    if @car.update(car_params)
      redirect_to car_path(@car)
    else
      render 'edit'
    end
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    @user = current_user
    @car.user = @user
    authorize @car
    if @car.save
      redirect_to car_path(@car)
    else
      render 'new'
    end
  end

  def destroy
    authorize @car
    @car.destroy
    @car.save
    redirect_to cars_path
  end

  def category
    @cars = Car.where(category: params[:category])
    authorize @cars
  end

  def mine
    @user = User.find(params[:user_id]) if params[:user_id].present?
    @cars = Car.where(user: @user)
    authorize @cars
        @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window: render_to_string(partial: "info_window", locals: { car: car }),
        image_url: car.photo.key,
        price: car.price_per_day
      }
    end
  end

private

  def set_car
    @car = Car.find(params[:id]) if params[:id].present?
  end

  def car_params
    params.require(:car).permit(:name, :category, :horse_power, :price_per_day, :transmision, :energy, :year_circulation, :city, :photo)
  end

  def filtering_params
    # params.permit(:name, "category", "energy", :city, :max_price, "transmision")
    # return {
    #   category: params["category"],
    #   name: params["name"],
    #   energy: params["energy"],
    #   city: params["city"],
    #   max_price: params["max_price"],
    #   transmision: params["transmision"]
    # }
  end
end

app/views/cars/_form.html.erb
<%= simple_form_for(car) do |f| %>
<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :category, collection: Car::CATEGORY %>
  <%= f.input :horse_power %>
  <%= f.input :price_per_day %>
  <%= f.input :transmision, collection: Car::TRANSMISION%>
  <%= f.input :energy, collection: Car::ENERGY %>
  <%= f.input :year_circulation %>
  <%= f.input :city %>
  <%= f.input :photo, as: :file %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default btn-primary m-3" %>
  <% if car.name %>
  <%= link_to "Cancel", car_path(car), class: "btn btn-secondary" %>
  <% else %>
  <%= link_to "Cancel", cars_path, class: "btn btn-secondary" %>
  <% end %>
<% end %>

app/views/cars/_info_window.html.erb
<div class="card-popup" style="background-image: url(<%= "#{cl_image_path car.photo.key}" =%> )">
    <div class="card-info">
        <h5 class="card-title">
            <%= car.name %>
        </h5>
        <p class="card-text"> <%= car.category %> - <%= car.transmision %> - <strong><%= car.price_per_day %>€</strong>  </p>
            <%= link_to 'Go!', car_path(car), class:"btn btn-primary" %>
    </div>
</div>

app/views/cars/edit.html.erb
<%= render "form", car: @car %>

app/views/cars/index.html.erb
<% if @current_user %>
  <%= link_to 'My cars', cars_mine_path(@current_user), class:"btn btn-primary mt-3" %>
  <%= link_to 'My dashboard', dashboard_path, class:"btn btn-primary mt-3" %>
<% elsif current_user %>
  <%= link_to 'My cars', cars_mine_path(current_user), class:"btn btn-primary mt-3" %>
  <%= link_to 'My dashboard', dashboard_path, class:"btn btn-primary mt-3" %>
<% end %>

<%= render 'shared/searchbar' %>
<%= render 'shared/warriorsearchbar' %>


<div class="card-grid mb-5">
<div class="flex-container">
  <% @cars.each do |car|%>
    <div class="card rounded" style="background-image: url(<%= "#{cl_image_path car.photo.key}" =%> )">
      <div class="card-body">
        <h5 class="card-title">
          <%= car.name %>
        </h5>
          <p class="card-text"> <%= car.category %> - <%= car.transmision %> -  <%= car.price_per_day %>€ </p>
          <%= link_to 'Go!', car_path(car), class:"btn btn-primary" %>
      </div>
    </div>
  <% end %>
  </div>
  <div id="map"style="width: 100%; height: 100vh"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>




<%= link_to "Add a car", new_car_path, class: "btn btn-primary" %>
<%= link_to "Back home", root_path, class: "btn btn-secondary" %>

app/views/cars/mine.html.erb
<% if @current_user %>
  <%= link_to 'My cars', cars_mine_path(@current_user), class:"btn btn-primary mt-3" %>
  <%= link_to 'My dashboard', dashboard_path, class:"btn btn-primary mt-3" %>
<% elsif current_user %>
  <%= link_to 'My cars', cars_mine_path(current_user), class:"btn btn-primary mt-3" %>
  <%= link_to 'My dashboard', dashboard_path, class:"btn btn-primary mt-3" %>
<% end %>

<%= render 'shared/searchbar' %>
<%= render 'shared/warriorsearchbar' %>

<div class="card-grid mb-5">
<div class="flex-container">
  <% @cars.each do |car|%>
    <div class="card rounded" style="background-image: url(<%= "#{cl_image_path car.photo.key}" =%> )">
      <div class="card-body">
        <h5 class="card-title">
          <%= car.name %>
        </h5>
          <p class="card-text"> <%= car.category %> - <%= car.transmision %> -  <%= car.price_per_day %>€ </p>
          <%= link_to 'Go!', car_path(car), class:"btn btn-primary" %>
      </div>
    </div>
  <% end %>
  </div>
  <div id="map"style="width: 100%; height: 100vh"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>


<%= link_to "Add a car", new_car_path, class: "btn btn-primary" %>
<%= link_to "Back home", root_path, class: "btn btn-secondary" %>

app/views/cars/new.html.erb
<%= render "form", car: @car %>

app/views/cars/show.html.erb
<div class="container">

  <div class="container-group d-flex mt-3">
    <ul class="list-group list-group-flush mt-0 mr-3 ml-3 mb-3">
      <li class="list-group-item"> <strong><u>Name:</u></strong> <%= @car.name %> </li>
      <li class="list-group-item"> <strong><u>Category:</u></strong> <%= @car.category %> </li>
      <li class="list-group-item"> <strong><u>Horse Power:</u></strong> <%= @car.horse_power %> hp</li>
      <li class="list-group-item"> <strong><u>Price per Day:</u></strong> <%= @car.price_per_day %> € </li>
      <li class="list-group-item"> <strong><u>Transmission:</u></strong> <%= @car.transmision %> </li>
      <li class="list-group-item"> <strong><u>Energy:</u></strong> <%= @car.energy %> </li>
      <li class="list-group-item"> <strong><u>Year:</u></strong> <%= @car.year_circulation %> </li>
      <li class="list-group-item"> <strong><u>City:</u></strong> <%= @car.city %> </li>
      <% unless current_user.cars.include? @car %>
        <%= link_to "Reserver!", new_booking_path(@car), class: "btn btn-danger"%>
      <%end %>
    </ul>
    <%= cl_image_tag @car.photo.key, height: 600, width: 800, crop: :fill, class:"rounded" %>
  </div>

  <div class="group-btn text-center m-4">
    <%= link_to 'Back to list', cars_path, class: "btn btn-secondary" %>
    <% if policy(@car).update? %>
    <%= link_to 'Edit car', edit_car_path, class: "btn btn-primary"%>
    <% end %>
    <% if policy(@car).destroy? %>
    <%= link_to "Delete car",
                car_path(@car),
                method: :delete,
                class: "btn btn-danger",
                data: { confirm: "Are you sure?" } %>
    <% end %>
  </div>
</div>